from dataclasses import dataclass


@dataclass
class RokuDevice():
    udn: (str|None) = None
    serial_number: (str | None) = None
    device_id: (str | None) = None
    advertising_id: (str | None) = None
    vendor_name: (str | None) = None
    model_name: (str | None) = None
    model_number: (str | None) = None
    model_region: (str | None) = None
    is_tv: (str | None) = None
    is_stick: (str | None) = None
    mobile_has_live_tv: (str | None) = None
    ui_resolution: (str | None) = None
    supports_ethernet: (str | None) = None
    wifi_mac: (str | None) = None
    wifi_driver: (str | None) = None
    has_wifi_5g_support:(str | None) = None
    network_type: (str | None) = None
    network_name: (str | None) = None
    friendly_device_name: (str | None) = None
    friendly_model_name: (str | None) = None
    default_device_name: (str | None) = None
    user_device_name: (str | None) = None
    user_device_location: (str | None) = None
    build_number: (str | None) = None
    software_version: (str | None) = None
    software_build: (str | None) = None
    lightning_base_build_number: (str | None) = None
    ui_build_number: (str | None) = None
    ui_software_version: (str | None) = None
    ui_software_build: (str | None) = None
    secure_device: (str | None) = None
    language: (str | None) = None
    country: (str | None) = None
    locale: (str | None) = None
    time_zone_auto: (str | None) = None
    time_zone: (str | None) = None
    time_zone_name: (str | None) = None
    time_zone_tz: (str | None) = None
    time_zone_offset: (str | None) = None
    clock_format: (str | None) = None
    uptime: (str | None) = None
    power_mode: (str | None) = None
    supports_suspend: (str | None) = None
    supports_find_remote: (str | None) = None
    find_remote_is_possible: (str | None) = None
    supports_audio_guide: (str | None) = None
    supports_rva: (str | None) = None
    has_hands_free_voice_remote: (str | None) = None
    developer_enabled: (str | None) = None
    keyed_developer_id: (str | None) = None
    search_enabled: (str | None) = None
    search_channels_enabled: (str | None) = None
    voice_search_enabled: (str | None) = None
    supports_private_listening: (str | None) = None
    headphones_connected: (str | None) = None
    supports_audio_settings: (str | None) = None
    supports_ecs_textedit: (str | None) = None
    supports_ecs_microphone: (str | None) = None
    supports_wake_on_wlan: (str | None) = None
    supports_airplay: (str | None) = None
    has_play_on_roku: (str | None) = None
    has_mobile_screensaver: (str | None) = None
    support_url: (str | None) = None
    grandcentral_version: (str | None) = None
    supports_trc: (str | None) = None
    trc_version: (str | None) = None
    trc_channel_version: (str | None) = None
    av_sync_calibration_enabled: (str | None) = None
